---
name: Test Python Code

on: # yamllint disable-line rule:truthy
  push:
    branches: [master, main]
    paths:
      - "src/**"
      - "tests/**"
      - "requirements.txt"
      - "dev-requirements.txt"
      - ".github/workflows/test-python.yaml"
  pull_request:
    branches: [master, main]
    paths:
      - "src/**"
      - "tests/**"
      - "requirements.txt"
      - "dev-requirements.txt"
      - ".github/workflows/test-python.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Run this locally with act - https://github.com/nektos/act
  # act -j testPython
  testPython:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python3
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make python_lint

      - name: Test
        run: make test
